# Is This Tweet Positive?

Bag of Words

**Credit:** http://ravikiranj.net/posts/2012/code/how-build-twitter-sentiment-analyzer/

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer(stop_words='english')

In [3]:
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [4]:
X_train = [
    'Hey Cici sweetheart! Just wanted to let u know I luv u! OH! and will the mixtape drop soon? FANTASY RIDE MAY 5TH!!!!',
    'I heard about that contest! Congrats girl!!',
    'UNC!!! NCAA Champs!! Franklin St.: I WAS THERE!! WILD AND CRAZY!!!!!! Nothing like it...EVER http://tinyurl.com/49955t3',
    'Do you Share More #jokes #quotes #music #photos or #news #articles on #Facebook or #Twitter?',
    'Good night #Twitter and #TheLegionoftheFallen. 5:45am cimes awfully early!',
    'I just finished a 2.66 mi run with a pace of 11\'14"/mi with Nike+ GPS. #nikeplus #makeitcount',
    'Disappointing day. Attended a car boot sale to raise some funds for the sanctuary, made a total of 88p after the entry fee - sigh',
    'no more taking Irish car bombs with strange Australian women who can drink like rockstars...my head hurts.',
    'Just had some bloodwork done. My arm hurts'
]

y_train = [
    'positive',
    'positive',
    'positive',
    'neutral',
    'neutral',
    'neutral',
    'negative',
    'negative',
    'negative'
]

In [5]:
X_train = vectorizer.fit_transform(X_train)

In [39]:
vectorizer.get_feature_names()

['11',
 '14',
 '45am',
 '49955t3',
 '5th',
 '66',
 '88p',
 'arm',
 'articles',
 'attended',
 'australian',
 'awfully',
 'bloodwork',
 'bombs',
 'boot',
 'car',
 'champs',
 'cici',
 'cimes',
 'com',
 'congrats',
 'contest',
 'crazy',
 'day',
 'disappointing',
 'drink',
 'drop',
 'early',
 'entry',
 'facebook',
 'fantasy',
 'fee',
 'finished',
 'franklin',
 'funds',
 'girl',
 'good',
 'gps',
 'head',
 'heard',
 'hey',
 'http',
 'hurts',
 'irish',
 'jokes',
 'just',
 'know',
 'let',
 'like',
 'luv',
 'makeitcount',
 'mi',
 'mixtape',
 'music',
 'ncaa',
 'news',
 'night',
 'nike',
 'nikeplus',
 'oh',
 'pace',
 'photos',
 'quotes',
 'raise',
 'ride',
 'rockstars',
 'run',
 'sale',
 'sanctuary',
 'share',
 'sigh',
 'soon',
 'st',
 'strange',
 'sweetheart',
 'taking',
 'thelegionofthefallen',
 'tinyurl',
 'total',
 'twitter',
 'unc',
 'wanted',
 'wild',
 'women']

In [6]:
X_train

<9x84 sparse matrix of type '<class 'numpy.int64'>'
	with 90 stored elements in Compressed Sparse Row format>

In [21]:
type(X_train)

scipy.sparse.csr.csr_matrix

In [22]:
X_train.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [23]:
vectorizer.inverse_transform(X_train)

[array(['hey', 'cici', 'sweetheart', 'just', 'wanted', 'let', 'know', 'luv',
        'oh', 'mixtape', 'drop', 'soon', 'fantasy', 'ride', '5th'], 
       dtype='<U20'), array(['heard', 'contest', 'congrats', 'girl'], 
       dtype='<U20'), array(['unc', 'ncaa', 'champs', 'franklin', 'st', 'wild', 'crazy', 'like',
        'http', 'tinyurl', 'com', '49955t3'], 
       dtype='<U20'), array(['share', 'jokes', 'quotes', 'music', 'photos', 'news', 'articles',
        'facebook', 'twitter'], 
       dtype='<U20'), array(['twitter', 'good', 'night', 'thelegionofthefallen', '45am', 'cimes',
        'awfully', 'early'], 
       dtype='<U20'), array(['just', 'finished', '66', 'mi', 'run', 'pace', '11', '14', 'nike',
        'gps', 'nikeplus', 'makeitcount'], 
       dtype='<U20'), array(['disappointing', 'day', 'attended', 'car', 'boot', 'sale', 'raise',
        'funds', 'sanctuary', 'total', '88p', 'entry', 'fee', 'sigh'], 
       dtype='<U20'), array(['like', 'car', 'taking', 'irish', 'bombs', '

In [7]:
X_test = ['This woman is my sweetheart']
X_test = vectorizer.transform(X_test)
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Predicting Sentiment from Tweet

In [8]:
X_test = ['Congrats @ravikiranj, i heard you wrote a new tech post on sentiment analysis']

In [9]:
X_test = vectorizer.transform(X_test)

In [10]:
X_test

<1x84 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [11]:
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
vectorizer.inverse_transform(X_test)

[array(['congrats', 'heard'], 
       dtype='<U20')]

In [12]:
# import
from sklearn import naive_bayes

# instantiate
clf = naive_bayes.MultinomialNB()

# fit
clf.fit(X_train, y_train)

# predict
clf.predict(X_test)

array(['positive'], 
      dtype='<U8')

Try another tweet!

In [13]:
X_test = ['I am very bored today.']
X_test = vectorizer.transform(X_test)

In [14]:
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
clf.predict(X_test)

array(['negative'], 
      dtype='<U8')

# TF-IDF

http://scikit-learn.org/stable/modules/feature_extraction.html

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
vectorizer = TfidfVectorizer(min_df=1)

In [3]:
corpus = [
    'new york times times',
    'new york post',
    'los angeles angeles times'
]

In [5]:
data = vectorizer.fit_transform(corpus)

In [6]:
data.toarray()

array([[ 0.        ,  0.        ,  0.40824829,  0.        ,  0.81649658,
         0.40824829],
       [ 0.        ,  0.        ,  0.51785612,  0.68091856,  0.        ,
         0.51785612],
       [ 0.84678897,  0.42339448,  0.        ,  0.        ,  0.32200242,
         0.        ]])

In [8]:
vectorizer.idf_

array([ 1.69314718,  1.69314718,  1.28768207,  1.69314718,  1.28768207,
        1.28768207])

In [9]:
vectorizer.vocabulary_

{'angeles': 0, 'los': 1, 'new': 2, 'post': 3, 'times': 4, 'york': 5}

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
data[0].toarray()

array([[ 0.        ,  0.        ,  0.40824829,  0.        ,  0.81649658,
         0.40824829]])

In [13]:
q = ['new new times']
q = vectorizer.transform(q)

In [14]:
cosine_similarity(data[0], q)

array([[ 0.73029674]])

In [15]:
cosine_similarity(data[1], q)

array([[ 0.46318459]])

In [16]:
cosine_similarity(data[2], q)

array([[ 0.14400386]])