In [1]:
from sklearn.decomposition import NMF

In [97]:
model = NMF(n_components=2, alpha=0.001, beta=0.1, init='random', max_iter=50000)

In [121]:
import pandas as pd

In [130]:
wine = pd.read_csv('data/reviews.csv')

In [131]:
wine.head()

id  username                         wine  rating  \
0   0  jadianes         Manzanilla La Gitana       4   
1   1  jadianes          Pol Roger Rose 1998       3   
2   2  jadianes             Molino Real 2002       4   
3   3  jadianes  Le Grappin Bagnum Rose 2013       2   
4   4  jadianes     La Bota de Amontillado 1       5   

                              comment  
0  Beautiful Manzanilla. Great price.  
1             Classy Rose. Not great.  
2        This can be great with time.  
3                        Drinkable...  
4                A treasure of a wine

In [132]:
wine_pivoted = wine.pivot('username', 'wine', 'rating').fillna(0)

In [133]:
wine_pivoted

wine      Chateau Latour 1982  JL Chave Hermitage 2001  \
username                                                 
carlos                    0.0                      5.0   
jadianes                  0.0                      0.0   
john                      0.0                      4.0   
lluis                     4.0                      0.0   
mari                      0.0                      0.0   
pepe                      0.0                      0.0   
teus                      0.0                      0.0   
yasset                    0.0                      0.0   

wine      La Bota de Amontillado 1  Le Grappin Bagnum Rose 2013  \
username                                                          
carlos                         0.0                          0.0   
jadianes                       5.0                          2.0   
john                           2.0                          3.0   
lluis                          0.0                          0.0   
mari                           0.0                          0.0   
pepe                           5.0                          0.0   
teus                           5.0                          0.0   
yasset                         0.0                          0.0   

wine      Manzanilla La Gitana  Molino Real 2002  Pol Roger Rose 1998  \
username                                                                
carlos                     4.0               4.0                  0.0   
jadianes                   4.0               4.0                  3.0   
john                       2.0               2.0                  4.0   
lluis                      4.0               0.0                  0.0   
mari                       3.0               5.0                  2.0   
pepe                       4.0               0.0                  2.0   
teus                       4.0               5.0                  0.0   
yasset                     4.0               1.0                  2.0   

wine      Raveneu Le Clos 1996  Rosseau Chambertin 2001  \
username                                                  
carlos                     0.0                      0.0   
jadianes                   0.0                      0.0   
john                       0.0                      0.0   
lluis                      0.0                      4.0   
mari                       5.0                      0.0   
pepe                       0.0                      4.0   
teus                       0.0                      0.0   
yasset                     4.0                      0.0   

wine      Vega Sicilia Unico 1989  Viña Tondonia Blanco Reserva 1981  
username                                                              
carlos                        0.0                                0.0  
jadianes                      0.0                                0.0  
john                          0.0                                0.0  
lluis                         0.0                                5.0  
mari                          0.0                                0.0  
pepe                          4.0                                0.0  
teus                          0.0                                4.0  
yasset                        5.0                                0.0

In [126]:
nP = model.fit_transform(wine_pivoted)
nP

array([[ 0.        ,  1.84495326],
       [ 0.28574789,  2.28386063],
       [ 0.        ,  1.83414984],
       [ 2.28446103,  0.        ],
       [ 0.        ,  2.05480984],
       [ 1.82225608,  0.72477885],
       [ 1.0336508 ,  1.74503858],
       [ 0.61786054,  1.20582117]])

In [127]:
nQ = model.components_.T
nQ

array([[ 0.90723266,  0.        ],
       [ 0.        ,  0.78003051],
       [ 1.08296833,  1.06159075],
       [ 0.        ,  0.47429907],
       [ 1.69424528,  1.57259929],
       [ 0.        ,  1.90227999],
       [ 0.11176775,  1.01987043],
       [ 0.        ,  0.71107548],
       [ 1.63090893,  0.        ],
       [ 0.93058718,  0.22230846],
       [ 1.54453667,  0.        ]])

In [128]:
import numpy as np

nR = np.dot(nP, nQ.T)

In [129]:
nR

array([[ 0.        ,  1.43911982,  1.95858531,  0.87505962,  2.90137219,
         3.50961766,  1.88161328,  1.31190102,  0.        ,  0.41014872,
         0.        ],
       [ 0.25923982,  1.78148096,  2.73398123,  1.08323298,  4.07572462,
         4.34454236,  2.36117932,  1.62399728,  0.46602879,  0.77363486,
         0.4413481 ],
       [ 0.        ,  1.43069283,  1.94711651,  0.86993557,  2.88438275,
         3.48906654,  1.8705952 ,  1.30421897,  0.        ,  0.40774703,
         0.        ],
       [ 2.07253765,  0.        ,  2.47399895,  0.        ,  3.87043731,
         0.        ,  0.25532906,  0.        ,  3.72574788,  2.12589014,
         3.52843383],
       [ 0.        ,  1.60281436,  2.18136712,  0.97459441,  3.2313925 ,
         3.90882364,  2.0956398 ,  1.46112489,  0.        ,  0.45680161,
         0.        ],
       [ 1.65321023,  0.56534961,  2.74286415,  0.34376194,  4.22713547,
         1.3787323 ,  0.94284998,  0.51537247,  2.9719337 ,  1.85689261,
         2.814

In [22]:
movies = pd.read_csv('data/u.data', delimiter='\t', header=None, names=['user_id', 'item_id', 'rating', 'timestamp'])

In [23]:
movies.head()

user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [40]:
movies_pivoted = movies.pivot('user_id', 'item_id', 'rating').fillna(0)

In [41]:
movies_pivoted.shape

(943, 1682)

In [42]:
movies_pivoted.head()

item_id  1     2     3     4     5     6     7     8     9     10    ...   \
user_id                                                              ...    
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...    
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...    
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
5         4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1682 columns]

In [43]:
nP = model.fit_transform(movies_pivoted)

In [44]:
nQ = model.components_.T

In [45]:
import numpy as np

nR = np.dot(nP, nQ.T)

In [46]:
nR.shape

(943, 1682)

In [47]:
nR

array([[  3.71042573e+00,   1.48786512e+00,   7.39786601e-01, ...,
          3.64852413e-03,   1.45795337e-02,   1.44342295e-02],
       [  2.11924673e+00,   2.29082328e-01,   5.51011318e-01, ...,
          4.84818973e-03,   0.00000000e+00,   0.00000000e+00],
       [  9.87536681e-01,   1.06748874e-01,   2.56762878e-01, ...,
          2.25918254e-03,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  1.04159131e+00,   1.12591968e-01,   2.70817263e-01, ...,
          2.38284302e-03,   0.00000000e+00,   0.00000000e+00],
       [  1.46210769e+00,   5.41872370e-01,   3.00710990e-01, ...,
          1.63556158e-03,   5.14912410e-03,   5.09780631e-03],
       [  2.43752863e+00,   9.44253061e-01,   4.92864317e-01, ...,
          2.54464959e-03,   9.13268865e-03,   9.04166940e-03]])

In [60]:
for each in nR[0]:
    print(each)

3.71042573031
1.48786511692
0.739786600685
2.56787865485
0.863099046058
0.219468112521
3.28832259769
2.74985781744
2.52466721532
0.920146689156
2.74738027649
3.41338620437
1.56377342455
1.52400834694
2.19349372556
0.281690321868
0.868315530769
0.107735424349
0.46278755539
0.587769064334
0.660433951992
3.62883499342
2.39910549656
1.54227306459
2.22166436551
0.871303140286
0.608178003698
3.37752702019
1.04353349335
0.545150637052
1.93199672502
1.05371175522
1.15845950487
0.0783825462871
0.0685258319573
0.102632291446
0.0707709979211
1.16747509164
1.00423679434
0.588781836071
0.381280626324
1.80669042194
0.480154603863
1.05321449891
1.00694080867
0.379285255418
1.80213096944
1.64773931851
0.975311536263
5.42125968444
1.07520333821
1.3119788523
1.22520806553
1.27312268037
1.74577634824
4.40202045274
0.510291387446
2.30337152581
1.04358580304
0.823373752413
0.757270700848
1.37377356812
0.923242263017
3.76115205381
1.46236252602
1.86163856821
1.09738895309
1.61808833372
3.84019025812
2.80477

In [5]:
restaurant_ratings = pd.read_csv('data/rating_final.csv')

In [6]:
restaurant_ratings_pivoted = restaurant_ratings.pivot('userID', 'placeID', 'rating').fillna(0)

In [13]:
restaurant_ratings_pivoted.head()

placeID  132560  132561  132564  132572  132583  132584  132594  132608  \
userID                                                                    
U1001       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
U1002       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
U1003       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
U1004       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
U1005       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

placeID  132609  132613   ...    135080  135081  135082  135085  135086  \
userID                    ...                                             
U1001       0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
U1002       0.0     0.0   ...       0.0     0.0     0.0     1.0     0.0   
U1003       0.0     0.0   ...       2.0     0.0     0.0     0.0     0.0   
U1004       0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
U1005       0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

placeID  135088  135104  135106  135108  135109  
userID                                           
U1001       0.0     0.0     0.0     0.0     0.0  
U1002       0.0     0.0     1.0     0.0     0.0  
U1003       0.0     0.0     0.0     0.0     0.0  
U1004       0.0     0.0     2.0     0.0     0.0  
U1005       0.0     0.0     0.0     0.0     0.0  

[5 rows x 130 columns]

In [7]:
nP = model.fit_transform(restaurant_ratings_pivoted)

In [8]:
nQ = model.components_.T

In [54]:
nP[0]

array([ 1.18727685,  0.59540847])

In [10]:
nQ

array([[  0.00000000e+00,   1.84894970e-22],
       [  0.00000000e+00,   1.85699437e-24],
       [  0.00000000e+00,   2.79359993e-22],
       [  0.00000000e+00,   5.01785525e-01],
       [  0.00000000e+00,   3.31275050e-12],
       [  0.00000000e+00,   8.78316405e-22],
       [  0.00000000e+00,   2.84983330e-22],
       [  0.00000000e+00,   4.17750540e-22],
       [  0.00000000e+00,   1.80140380e-22],
       [  0.00000000e+00,   6.94938928e-22],
       [  0.00000000e+00,   1.65719648e-23],
       [  0.00000000e+00,   5.54727378e-22],
       [  0.00000000e+00,   6.66709663e-25],
       [  0.00000000e+00,   7.02541123e-22],
       [  0.00000000e+00,   3.06102423e-22],
       [  0.00000000e+00,   9.77043046e-24],
       [  0.00000000e+00,   5.57812903e-22],
       [  0.00000000e+00,   1.54003140e-22],
       [  0.00000000e+00,   1.36216759e-24],
       [  0.00000000e+00,   1.72137596e-22],
       [  0.00000000e+00,   2.03880013e-22],
       [  0.00000000e+00,   7.27565022e-01],
       [  

In [11]:
import numpy as np

nR = np.dot(nP, nQ.T)

In [14]:
nR.shape

(138, 130)

In [15]:
nR

array([[  1.16399670e-23,   1.16906118e-25,   1.75869636e-23, ...,
          1.59717936e-01,   6.57581696e-02,   1.39663123e-13],
       [  7.51985385e-23,   7.55257229e-25,   1.13618360e-22, ...,
          1.81052858e-01,   7.40647083e-02,   9.02275985e-13],
       [  2.10334997e-22,   2.11250152e-24,   3.17797631e-22, ...,
          3.92778841e-03,   0.00000000e+00,   2.52372214e-12],
       ..., 
       [  1.25596763e-22,   1.26143227e-24,   1.89765632e-22, ...,
          2.34538958e-03,   0.00000000e+00,   1.50698332e-12],
       [  1.98039791e-22,   1.98901450e-24,   2.99220658e-22, ...,
          1.72535899e-01,   6.96076430e-02,   2.37619707e-12],
       [  3.32811475e-23,   3.34259518e-25,   5.02848788e-23, ...,
          6.21490990e-04,   0.00000000e+00,   3.99326646e-13]])

In [16]:
nR[0][10]

1.0432794550870253e-24

In [93]:
R = [
    [5,3,0,1],
    [4,0,0,1],
    [1,1,0,5],
    [1,0,0,4],
    [0,1,5,4],
]

In [97]:
nP = model.fit_transform(R)

In [98]:
nQ = model.components_.T

In [122]:
nP

array([[ 2.16633722,  0.55407869],
       [ 1.70798369,  0.5302996 ],
       [ 0.10718956,  2.21074108],
       [ 0.13966648,  1.77323892],
       [ 0.45691301,  1.81502338]])

In [123]:
nQ

array([[ 2.20791263,  0.37259101],
       [ 1.27888886,  0.32519351],
       [ 1.22086951,  2.40506934],
       [-0.1145428 ,  2.24998977]])

In [124]:
import numpy as np

nR = np.dot(nP, nQ.T)

In [125]:
nR

array([[ 4.98952806,  2.95068734,  3.97741274,  0.99853305],
       [ 3.96866364,  2.35677131,  3.36063254,  0.99753145],
       [ 1.06036742,  0.85600219,  5.44785004,  4.96186702],
       [ 0.96906427,  0.7552637 ,  4.4352771 ,  3.97377164],
       [ 1.68508538,  1.17457478,  4.92308823,  4.03144794]])

In [112]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if e < 0.001:
            break
    return P, Q.T

In [119]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]

R = np.array(R)

N = len(R)
M = len(R[0])
K = 2

P = np.random.rand(N,K)
Q = np.random.rand(M,K)

nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)

In [120]:
nP

array([[ 2.16633722,  0.55407869],
       [ 1.70798369,  0.5302996 ],
       [ 0.10718956,  2.21074108],
       [ 0.13966648,  1.77323892],
       [ 0.45691301,  1.81502338]])

In [121]:
nQ

array([[ 2.20791263,  0.37259101],
       [ 1.27888886,  0.32519351],
       [ 1.22086951,  2.40506934],
       [-0.1145428 ,  2.24998977]])

In [116]:
nR

array([[ 5.04652403,  2.7842778 ,  5.65453283,  0.99807943],
       [ 3.92590359,  2.16772918,  4.51870047,  0.99925429],
       [ 1.12095544,  0.6551286 ,  3.80705983,  4.96614125],
       [ 0.93923822,  0.54750922,  3.09133145,  3.97776561],
       [ 2.6453359 ,  1.48656641,  4.84756123,  4.0261405 ]])