* http://grouplens.org/datasets/movielens/
* http://jmcauley.ucsd.edu/data/amazon/

In [1]:
from sklearn.decomposition import NMF

In [92]:
model = NMF(n_components=2, alpha=0.0002, beta=0.02, eta=0.0001, init='random', max_iter=5000, nls_max_iter=20000, sparseness=None, tol=0.001)

In [93]:
R = [
    [5,3,0,1],
    [4,0,0,1],
    [1,1,0,5],
    [1,0,0,4],
    [0,1,5,4],
]

In [97]:
nP = model.fit_transform(R)

In [98]:
nQ = model.components_.T

In [122]:
nP

array([[ 2.16633722,  0.55407869],
       [ 1.70798369,  0.5302996 ],
       [ 0.10718956,  2.21074108],
       [ 0.13966648,  1.77323892],
       [ 0.45691301,  1.81502338]])

In [123]:
nQ

array([[ 2.20791263,  0.37259101],
       [ 1.27888886,  0.32519351],
       [ 1.22086951,  2.40506934],
       [-0.1145428 ,  2.24998977]])

In [124]:
import numpy as np

nR = np.dot(nP, nQ.T)

In [125]:
nR

array([[ 4.98952806,  2.95068734,  3.97741274,  0.99853305],
       [ 3.96866364,  2.35677131,  3.36063254,  0.99753145],
       [ 1.06036742,  0.85600219,  5.44785004,  4.96186702],
       [ 0.96906427,  0.7552637 ,  4.4352771 ,  3.97377164],
       [ 1.68508538,  1.17457478,  4.92308823,  4.03144794]])

In [112]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if e < 0.001:
            break
    return P, Q.T

In [119]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]

R = np.array(R)

N = len(R)
M = len(R[0])
K = 2

P = np.random.rand(N,K)
Q = np.random.rand(M,K)

nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)

In [120]:
nP

array([[ 2.16633722,  0.55407869],
       [ 1.70798369,  0.5302996 ],
       [ 0.10718956,  2.21074108],
       [ 0.13966648,  1.77323892],
       [ 0.45691301,  1.81502338]])

In [121]:
nQ

array([[ 2.20791263,  0.37259101],
       [ 1.27888886,  0.32519351],
       [ 1.22086951,  2.40506934],
       [-0.1145428 ,  2.24998977]])

In [116]:
nR

array([[ 5.04652403,  2.7842778 ,  5.65453283,  0.99807943],
       [ 3.92590359,  2.16772918,  4.51870047,  0.99925429],
       [ 1.12095544,  0.6551286 ,  3.80705983,  4.96614125],
       [ 0.93923822,  0.54750922,  3.09133145,  3.97776561],
       [ 2.6453359 ,  1.48656641,  4.84756123,  4.0261405 ]])